apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-test
  labels:
    app: golang-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: golang-test
  template:
    metadata:
      labels:
        app: golang-test
    spec:
      containers:
        - name: golang-test
          image: rootduck/golang-test:1.0.0
          envFrom:
            - configMapRef:
                name: style2-configmap
            - configSecret:
                name: style2-secret